#!/bin/bash 
SAMPLESCHEMES=(uniform importance_distance importance_distance_hullapprox)
COLORS=("red" "green" "blue")
function escape_ {
  echo $1 | sed 's/_/\\\\_/g' 
}
function join { local IFS="$1"; shift; echo "$*";}
FILES=()
for i in "${SAMPLESCHEMES[@]}"; do
  FILES+=(/cygdrive/c/Users/Wouter/Documents/Data/Experiments/IBSSimilarity/$i/$(basename "$1" | sed 's/_\(.*\)//')/ibsSimilarities.txt)
done
PLOTDATA=()
for i in "${!SAMPLESCHEMES[@]}"; do
  DATA=()
  DATA=($(sed 's/ibs_\([^_]*\)_\([^_]*\)_\([^_]*\)_\([^ ]*\)/\1 \3/' ${FILES[$i]}))
  NEWDATA=()
  TMP=()
  z=0
  min=100
  max=-100
  for ((j=0;j<${#DATA[@]};j++)); do
    NEWDATA[$((z++))]=${DATA[$j]}
    if [[ $(($j % 3)) == 2 ]]; then
      if [[ `echo "${DATA[$j]} > $max" | bc` == 1 ]]; then max="${DATA[$j]}"; fi
      if [[ `echo "${DATA[$j]} < $min" | bc` == 1 ]]; then min="${DATA[$j]}"; fi
      NEWDATA[$((z++))]="\n"
      if [[ "${NEWDATA[$((z-6))]}" != "${NEWDATA[$((z-4))]}" ]]; then
        for ((iz=0;iz<5;iz++)); do
          if [[ $iz == 0 || $iz == 1 ]]; then
            NEWDATA[$((z++))]=${NEWDATA[$((z-6+2))]}
          elif [[ $iz == 2 || $iz == 3 ]]; then
            NEWDATA[$((z++))]=${NEWDATA[$((z-6-2))]}
          else
            NEWDATA[$((z++))]=${NEWDATA[$((z-6))]}
          fi
        done
        NEWDATA[$((z++))]="\n"
      fi
      continue
    fi
    oldZ=$z
    #if [[ $(($j % 3)) == 0 ]]; then
      for k in "${!TMP[@]}"; do 
        if [[ ${DATA[$j]} == ${TMP[$k]} ]]; then
          NEWDATA[$((z++))]=$k
        fi
      done
      if [[ $oldZ == $z ]]; then
        TMP+=(${DATA[$j]})
        NEWDATA[$((z++))]=$((${#TMP[@]}-1))
      fi
  done
  RESULT=$(join " " ${NEWDATA[@]})
  RESULT=$(echo $RESULT | sed 's/ \\n /\\n/g' )
  RESULT=$(printf "$RESULT")
  RESULT=$(echo "$RESULT" | sed 's/\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^ ]*\)/\2 \4 \1 \3/')
  RESULT=$(sort <<<"$RESULT")
  PLOTDATA+=("$RESULT")
  #PLOTDATA=$(join "$PLOTDATA" "$RESULT" -j 3)
done
#echo "${PLOTDATA[@]}"
#echo "$PLOTDATA"
echo $(escape_ "${SAMPLESCHEMES[$i]}")
{
  # TODO: make column with unique index of occurrence
  for i in "${!SAMPLESCHEMES[@]}"; do
    echo "\$${SAMPLESCHEMES[$i]} << EOD"
    #echo "$(sed 's/ibs_\([^_]*\)_\([^_]*\)_\([^_]*\)_\([^ ]*\)/\1 \3/' ${FILES[$i]})"
    echo "${PLOTDATA[$i]}"
    echo "EOD"
  done
  echo "set palette rgbformula 10,13,33"
  echo "set cbrange [$min:$max]"
  #echo "set yrange [-0.5:`echo "${#TMP[@]}+0.5" | br`]"
  echo "unset key"
  echo "set xtics rotate by -90"
  #echo "print \$uniform"
  #echo "plot \\"
  for i in "${!SAMPLESCHEMES[@]}"; do
    echo "set title \"$(basename "$1" | sed 's/_\(.*\)//')\""
    echo "set term x11 $i"
    echo "plot \"\$${SAMPLESCHEMES[$i]}\" u 1:2:5:xtic(3):ytic(4) title '$(escape_ "${SAMPLESCHEMES[$i]}")' w image"
  done
} | gnuplot -persist
